const canvas = document.querySelector('#game'), ctx = canvas.getContext('2d');
const overlay = document.querySelector('#message'), start = document.querySelector('#start-button');
const newCave = document.querySelector('#new-cave'), soundToggle = document.querySelector('#sound-toggle'), crystalCount = document.querySelector('#crystal-count');
const crystalTotal = document.querySelector('#crystal-total'), depth = document.querySelector('#depth'), healthDisplay = document.querySelector('#health'), hungerDisplay = document.querySelector('#hunger'), shardsDisplay = document.querySelector('#shards'), foodDisplay = document.querySelector('#food-count'), caveName = document.querySelector('#cave-name'), levelDisplay = document.querySelector('#level');
const COLS = 45, ROWS = 30, TILE = 20;
const THEMES = [{name:'BASALT',walls:['#182327','#1d2b2d','#132024'],floor:'#0e1719',line:'#142124',mark:'#26363a',crystal:'#74f0ee',glow:'#42d9e5'},{name:'FROST',walls:['#23343d','#2a3e48','#1c2d36'],floor:'#101c25',line:'#19303c',mark:'#638397',crystal:'#c8f5ff',glow:'#7fd9ff'},{name:'EMBER',walls:['#3a2521','#462a23','#2f1e1c'],floor:'#211311',line:'#38201d',mark:'#70402d',crystal:'#ffbf70',glow:'#ef653e'},{name:'VERDANT',walls:['#1d3024','#263d2a','#17291e'],floor:'#0e1d15',line:'#183022',mark:'#3b6744',crystal:'#b5ef8d',glow:'#71d26e'}];
let map, player, crystals, foods, monsters, exit, health, maxHealth, hunger, shards, weapons, inventory, theme, level = 1, shopOpen = false, inventoryOpen = false, running = false, won = false, pulse = 0, burst = 0;
let audio, master, muted = false, ambienceStarted = false;
let heldDirection = null, moveTimer = 0;

function ensureAudio() {
  if (!audio) { audio = new AudioContext(); master = audio.createGain(); master.gain.value = muted ? .0001 : .22; master.connect(audio.destination); }
  if (audio.state === 'suspended') audio.resume();
  if (!ambienceStarted) startAmbience();
}
function tone(freq, duration=.12, type='sine', volume=.12, slide=1) {
  if (!audio || muted) return; const t=audio.currentTime, osc=audio.createOscillator(), gain=audio.createGain(); osc.type=type; osc.frequency.setValueAtTime(freq,t); osc.frequency.exponentialRampToValueAtTime(Math.max(20,freq*slide),t+duration); gain.gain.setValueAtTime(volume,t); gain.gain.exponentialRampToValueAtTime(.001,t+duration); osc.connect(gain).connect(master); osc.start(t); osc.stop(t+duration+.02);
}
function noise(duration=.12, volume=.08) {
  if (!audio || muted) return; const buffer=audio.createBuffer(1, audio.sampleRate*duration, audio.sampleRate), data=buffer.getChannelData(0); for(let i=0;i<data.length;i++) data[i]=(Math.random()*2-1)*(1-i/data.length); const source=audio.createBufferSource(), gain=audio.createGain(); source.buffer=buffer; gain.gain.value=volume; source.connect(gain).connect(master); source.start();
}
function sound(kind) { if (muted || !audio) return; if(kind==='step') tone(100,.045,'triangle',.035,.8); if(kind==='crystal'){tone(740,.2,'sine',.1,1.5);setTimeout(()=>tone(1110,.25,'sine',.07,1.2),60)} if(kind==='food'){tone(280,.13,'triangle',.08,1.5);setTimeout(()=>tone(420,.18,'sine',.06,1.2),60)} if(kind==='buy'){tone(392,.12,'triangle',.09,1.3);setTimeout(()=>tone(523,.25,'sine',.08,1.1),70)} if(kind==='blade'){tone(340,.12,'sawtooth',.1,2.4)} if(kind==='burst'){tone(180,.35,'sawtooth',.12,4);noise(.18,.08)} if(kind==='hurt'){noise(.25,.16);tone(90,.3,'sawtooth',.12,.45)} if(kind==='win'){[440,554,659,880].forEach((f,i)=>setTimeout(()=>tone(f,.35,'sine',.1,1.02),i*110));} if(kind==='lose'){tone(210,.8,'sawtooth',.13,.25);} }
function startAmbience() { ambienceStarted=true; const now=audio.currentTime; [55,82.4].forEach((frequency,index)=>{const osc=audio.createOscillator(), gain=audio.createGain(), filter=audio.createBiquadFilter();osc.type='sine';osc.frequency.value=frequency;gain.gain.value=index?.018:.035;filter.type='lowpass';filter.frequency.value=230;osc.connect(filter).connect(gain).connect(master);osc.start(now);}); const chime=()=>{if(!muted&&running){tone([220,277,330,415][Math.floor(Math.random()*4)],1.8,'sine',.012,.99)} setTimeout(chime,5000+Math.random()*6000)};chime(); }

function makeCave(newExpedition = true) {
  if (newExpedition) { level = 1; shards = 0; maxHealth = 3; weapons = {lance: false, blade: false}; inventory = {food: 0}; }
  levelDisplay.textContent = level;
  theme = THEMES[Math.floor(Math.random()*THEMES.length)]; caveName.textContent = theme.name;
  map = Array.from({length: ROWS}, (_, y) => Array.from({length: COLS}, (_, x) => x === 0 || y === 0 || x === COLS - 1 || y === ROWS - 1 || Math.random() < .43 ? 1 : 0));
  for (let pass = 0; pass < 5; pass++) map = map.map((row, y) => row.map((cell, x) => {
    if (x === 0 || y === 0 || x === COLS - 1 || y === ROWS - 1) return 1;
    let n = 0; for (let yy = -1; yy <= 1; yy++) for (let xx = -1; xx <= 1; xx++) if (map[y + yy]?.[x + xx]) n++;
    return n >= 5 ? 1 : 0;
  }));
  let x = 2, y = 2; map[y][x] = 0;
  while (x < COLS - 3 || y < ROWS - 3) { if ((Math.random() < .58 && x < COLS - 3) || y >= ROWS - 3) x++; else y++; map[y][x] = 0; if (Math.random() < .35) map[Math.max(1, y - 1)][x] = 0; }
  player = {x: 2, y: 2, bob: 0}; exit = {x: COLS - 3, y: ROWS - 3}; crystals = [];
  const reachable = [], seen = new Set(['2,2']), queue = [{x: 2, y: 2}];
  while (queue.length) { const p = queue.shift(); reachable.push(p); for (const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]) { const q={x:p.x+dx,y:p.y+dy}, id=`${q.x},${q.y}`; if (!seen.has(id) && !map[q.y]?.[q.x]) { seen.add(id); queue.push(q); } } }
  for (let i = 0; i < 10 + level; i++) { let p; do p = reachable[Math.floor(Math.random() * reachable.length)]; while (crystals.some(c=>c.x===p.x&&c.y===p.y) || Math.abs(p.x-player.x)+Math.abs(p.y-player.y)<5 || (p.x===exit.x&&p.y===exit.y)); crystals.push(p); }
  foods = [];
  for (let i = 0; i < 7 + Math.floor(level / 3); i++) { let p; do p = reachable[Math.floor(Math.random() * reachable.length)]; while (foods.some(f=>f.x===p.x&&f.y===p.y) || crystals.some(c=>c.x===p.x&&c.y===p.y) || Math.abs(p.x-player.x)+Math.abs(p.y-player.y)<4 || (p.x===exit.x&&p.y===exit.y)); foods.push(p); }
  monsters = [];
  const monsterTypes = Array.from({length: Math.min(16, 7 + level)}, (_, i) => ['crawler', 'crawler', 'crawler', 'stalker', 'stalker', 'wisp', 'wisp', 'wisp'][i % 8]);
  for (const type of monsterTypes) { let p; do p = reachable[Math.floor(Math.random() * reachable.length)]; while (Math.abs(p.x-player.x)+Math.abs(p.y-player.y)<12 || (p.x===exit.x&&p.y===exit.y) || crystals.some(c=>c.x===p.x&&c.y===p.y) || foods.some(f=>f.x===p.x&&f.y===p.y) || monsters.some(m=>m.x===p.x&&m.y===p.y)); monsters.push({...p, type, cool: 0}); }
  health = maxHealth; hunger = 100; shopOpen = false; inventoryOpen = false; updateHunger(); shardsDisplay.textContent=shards; foodDisplay.textContent=inventory.food; healthDisplay.textContent = '♥'.repeat(health) + '♡'.repeat(maxHealth-health); crystalTotal.textContent = crystals.length; crystalCount.textContent = 0; depth.textContent = 300 + level * 180 + Math.floor(Math.random() * 120); won = false; burst = 0;
}
function updateHunger() { hungerDisplay.textContent = '█'.repeat(Math.ceil(hunger / 20)) + '░'.repeat(5-Math.ceil(hunger / 20)); }
function starve() { won = true; sound('lose'); overlay.innerHTML = '<p class="eyebrow">SUPPLIES EXHAUSTED</p><h2>You run out of strength.</h2><p>Food is scarce in the lower caves. Search for the red supply packs.</p><button id="again">Try another descent</button>'; overlay.classList.remove('hidden'); document.querySelector('#again').onclick = begin; }
function move(dx, dy) { if (!running || won || shopOpen || inventoryOpen) return; const nx = player.x + dx, ny = player.y + dy; if (!map[ny]?.[nx]) { sound('step'); player.x = nx; player.y = ny; player.bob = .35; hunger=Math.max(0,hunger-1); updateHunger(); const found = crystals.findIndex(c => c.x === nx && c.y === ny); if (found >= 0) { crystals.splice(found, 1); crystalCount.textContent = +crystalCount.textContent + 1; shards++; shardsDisplay.textContent=shards; sound('crystal'); } const meal=foods.findIndex(f=>f.x===nx&&f.y===ny); if(meal>=0){foods.splice(meal,1);inventory.food++;foodDisplay.textContent=inventory.food;sound('food');} if(!hunger) starve(); if (!won && nx === exit.x && ny === exit.y && !crystals.length) victory(); if(!won) monsterTurn(); } }
function monsterTurn() {
  for (const m of monsters) { if (m.cool) { m.cool--; continue; } const dx=player.x-m.x, dy=player.y-m.y, sight=m.type==='stalker'?14:m.type==='crawler'?7:10, choices=Math.abs(dx)+Math.abs(dy)<sight ? [[Math.sign(dx),0],[0,Math.sign(dy)]] : [[0,1],[1,0],[0,-1],[-1,0]].sort(()=>Math.random()-.5); for (const [mx,my] of choices) { const nx=m.x+mx, ny=m.y+my; if (!map[ny]?.[nx] && !(nx===player.x&&ny===player.y) && !monsters.some(o=>o!==m&&o.x===nx&&o.y===ny)) { m.x=nx;m.y=ny;break; } } }
  if (monsters.some(m=>Math.abs(m.x-player.x)+Math.abs(m.y-player.y)<=1)) hurt();
}
function hurt() { health--; sound('hurt'); healthDisplay.textContent = '♥'.repeat(Math.max(0,health)) + '♡'.repeat(Math.max(0,maxHealth-health)); if (health <= 0) gameOver(); }
function lanternBurst() { if (!running || won || shopOpen || inventoryOpen) return; burst = 1; sound('burst'); const range=weapons.lance?7:4, wispRange=weapons.lance?5:2, before=monsters.length; monsters = monsters.filter(m => { const distance=Math.abs(m.x-player.x)+Math.abs(m.y-player.y); return distance>range || (m.type==='wisp' && distance>wispRange); }); if (before === monsters.length) monsterTurn(); }
function bladeStrike() { if (!running || won || shopOpen || inventoryOpen || !weapons.blade) return; sound('blade'); const before=monsters.length; monsters=monsters.filter(m=>Math.abs(m.x-player.x)+Math.abs(m.y-player.y)>1); if(before===monsters.length) monsterTurn(); }
function openShop() { if(!running || won) return; shopOpen=true; overlay.innerHTML=`<p class="eyebrow">FIELD FORGE · ${shards} SHARDS</p><h2>Arm yourself.</h2><p><b>1 — Pulse Lance · 5 shards</b><br>Expands lantern burst to 7 tiles and reaches wisps at 5 tiles.</p><p><b>2 — Crystal Blade · 8 shards</b><br>Press F to defeat a monster beside you.</p><p><b>3 — Heart Vessel · 6 shards</b><br>Adds one permanent heart and fully restores your lantern.</p><button id="buy-lance" ${weapons.lance||shards<5?'disabled':''}>${weapons.lance?'Pulse Lance installed':'Buy Pulse Lance'}</button><button id="buy-blade" ${weapons.blade||shards<8?'disabled':''}>${weapons.blade?'Crystal Blade installed':'Buy Crystal Blade'}</button><button id="buy-heart" ${maxHealth>=6||shards<6?'disabled':''}>${maxHealth>=6?'Heart capacity maxed':'Buy Heart Vessel'}</button><small>Press B or Escape to return to the cave</small>`;overlay.classList.remove('hidden');document.querySelector('#buy-lance').onclick=()=>buyWeapon('lance',5);document.querySelector('#buy-blade').onclick=()=>buyWeapon('blade',8);document.querySelector('#buy-heart').onclick=buyHeart; }
function buyWeapon(name,cost){if(!weapons[name]&&shards>=cost){shards-=cost;shardsDisplay.textContent=shards;weapons[name]=true;sound('buy');openShop();}}
function buyHeart(){if(shards>=6&&maxHealth<6){shards-=6;maxHealth++;health=maxHealth;shardsDisplay.textContent=shards;healthDisplay.textContent='♥'.repeat(health);sound('buy');openShop();}}
function closeShop(){shopOpen=false;overlay.classList.add('hidden');}
function openInventory(){if(!running||won)return;inventoryOpen=true;overlay.innerHTML=`<p class="eyebrow">EXPEDITION INVENTORY</p><h2>What you carry.</h2><p><b>Food supplies · ${inventory.food}</b><br>Restores 30 hunger when consumed.</p><p><b>Crystal shards · ${shards}</b><br>${weapons.lance?'Pulse Lance installed.':'No Pulse Lance.'}<br>${weapons.blade?'Crystal Blade installed.':'No Crystal Blade.'}</p><button id="eat-food" ${!inventory.food||hunger>=100?'disabled':''}>Eat food supply</button><small>Press I or Escape to return to the cave</small>`;overlay.classList.remove('hidden');document.querySelector('#eat-food').onclick=useFood;}
function useFood(){if(!inventory.food||hunger>=100)return;inventory.food--;foodDisplay.textContent=inventory.food;hunger=Math.min(100,hunger+30);updateHunger();sound('food');openInventory();}
function closeInventory(){inventoryOpen=false;overlay.classList.add('hidden');}
function victory() { won = true; sound('win'); overlay.innerHTML = `<p class="eyebrow">LEVEL ${level} CLEARED</p><h2>You found the next descent.</h2><p>Your shards and forged weapons carry into the deeper cave.</p><button id="again">Descend to level ${level + 1}</button>`; overlay.classList.remove('hidden'); document.querySelector('#again').onclick = nextLevel; }
function gameOver() { won = true; sound('lose'); overlay.innerHTML = '<p class="eyebrow">LANTERN EXTINGUISHED</p><h2>The dark takes you.</h2><p>Something unseen carries on through the tunnels.</p><button id="again">Try another descent</button>'; overlay.classList.remove('hidden'); document.querySelector('#again').onclick = begin; }
function draw() {
  pulse += .04; ctx.fillStyle = '#080d0e'; ctx.fillRect(0, 0, 900, 600);
  for (let y=0;y<ROWS;y++) for(let x=0;x<COLS;x++) { const px=x*TILE, py=y*TILE, seed=(x*17+y*31)%3; if (map[y][x]) { ctx.fillStyle=theme.walls[seed]; ctx.fillRect(px,py,TILE,TILE); ctx.fillStyle=theme.mark; ctx.fillRect(px+3,py+3,4,3); if((x*13+y*7)%11===0)ctx.fillRect(px+13,py+13,2,2); } else { ctx.fillStyle=theme.floor; ctx.fillRect(px,py,TILE,TILE); ctx.strokeStyle=theme.line; ctx.strokeRect(px+.5,py+.5,TILE-1,TILE-1); if((x*5+y*9)%19===0){ctx.fillStyle=theme.mark;ctx.globalAlpha=.32;ctx.fillRect(px+9,py+10,2,2);ctx.globalAlpha=1;} } }
  const lit = !crystals.length; ctx.save(); ctx.translate(exit.x*TILE+10, exit.y*TILE+10); ctx.strokeStyle=lit?'#e8d795':'#4f5147'; ctx.lineWidth=3; ctx.strokeRect(-7,-9,14,18); ctx.fillStyle=lit?'#b88e4b':'#232926'; ctx.fillRect(-4,-5,8,12); ctx.restore();
  crystals.forEach(c=>{ ctx.save(); ctx.shadowBlur=11+Math.sin(pulse+c.x)*2; ctx.shadowColor=theme.glow; ctx.fillStyle=theme.crystal; ctx.beginPath();ctx.moveTo(c.x*TILE+10,c.y*TILE+2);ctx.lineTo(c.x*TILE+15,c.y*TILE+10);ctx.lineTo(c.x*TILE+10,c.y*TILE+18);ctx.lineTo(c.x*TILE+5,c.y*TILE+10);ctx.fill();ctx.restore(); });
  foods.forEach(f=>{const fx=f.x*TILE+10,fy=f.y*TILE+10;ctx.save();ctx.shadowBlur=6;ctx.shadowColor='#d86b4d';ctx.fillStyle='#d85645';ctx.beginPath();ctx.arc(fx,fy-2,6,Math.PI,0);ctx.fill();ctx.fillStyle='#e9c8a1';ctx.fillRect(fx-2,fy-1,4,8);ctx.fillStyle='#f4e9ce';ctx.fillRect(fx-3,fy-4,2,2);ctx.fillRect(fx+2,fy-5,2,2);ctx.restore();});
  monsters.forEach(m=>{ const mx=m.x*TILE+10,my=m.y*TILE+10;ctx.save();ctx.translate(mx,my);if(m.type==='wisp'){ctx.globalAlpha=.75;ctx.shadowBlur=12;ctx.shadowColor='#9a76ea';ctx.fillStyle='#7c68bf';ctx.beginPath();ctx.arc(0,0,6+Math.sin(pulse+m.x)*2,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e5d7ff';ctx.beginPath();ctx.arc(-2,-2,2,0,Math.PI*2);ctx.fill();}else if(m.type==='stalker'){ctx.shadowBlur=8;ctx.shadowColor='#e9af55';ctx.fillStyle='#3c3020';ctx.beginPath();ctx.moveTo(-8,8);ctx.lineTo(-6,-7);ctx.lineTo(0,-10);ctx.lineTo(6,-7);ctx.lineTo(8,8);ctx.fill();ctx.fillStyle='#ffd36a';ctx.fillRect(-4,-3,3,3);ctx.fillRect(2,-3,3,3);}else{ctx.shadowBlur=7;ctx.shadowColor='#d84c5c';ctx.fillStyle='#442034';ctx.beginPath();ctx.arc(0,2,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f06a68';ctx.fillRect(-4,-1,3,3);ctx.fillRect(2,-1,3,3);}ctx.restore(); });
  ctx.save();ctx.translate(player.x*TILE+10,player.y*TILE+11+Math.sin(pulse*4)*player.bob*3);ctx.shadowBlur=12;ctx.shadowColor='#ffcc72';ctx.fillStyle='#f0b65a';ctx.beginPath();ctx.arc(0,-3,5,0,7);ctx.fill();ctx.fillStyle='#295e62';ctx.fillRect(-5,1,10,8);ctx.restore();
  const gx=player.x*TILE+10, gy=player.y*TILE+10, g=ctx.createRadialGradient(gx,gy,35,gx,gy,burst?220:145); g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(.5,'rgba(0,0,0,.08)');g.addColorStop(1,'rgba(0,0,0,.92)');ctx.fillStyle=g;ctx.fillRect(0,0,900,600); if(burst) burst=Math.max(0,burst-.05); requestAnimationFrame(draw);
}
function begin() { ensureAudio(); makeCave(true); overlay.classList.add('hidden'); running = true; }
function nextLevel() { level++; makeCave(false); overlay.classList.add('hidden'); running = true; }
const directions = {arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1],arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0]};
window.addEventListener('keydown', e => { const k=e.key.toLowerCase(); if (directions[k]) { e.preventDefault(); if (!e.repeat) { heldDirection=directions[k]; move(...heldDirection); clearInterval(moveTimer); moveTimer=setInterval(()=>move(...heldDirection),95); } } if (k === ' ') { e.preventDefault(); if (!e.repeat) lanternBurst(); } if(k==='f'&&!e.repeat) bladeStrike(); if(k==='b'&&!e.repeat&&!inventoryOpen) shopOpen?closeShop():openShop(); if(k==='i'&&!e.repeat&&!shopOpen) inventoryOpen?closeInventory():openInventory(); if(k==='escape'&&shopOpen) closeShop(); if(k==='escape'&&inventoryOpen) closeInventory(); if(shopOpen&&k==='1') buyWeapon('lance',5); if(shopOpen&&k==='2') buyWeapon('blade',8); if(shopOpen&&k==='3') buyHeart(); });
window.addEventListener('keyup', e => { if (directions[e.key.toLowerCase()]) { heldDirection=null; clearInterval(moveTimer); } });
start.onclick = begin; newCave.onclick = begin; soundToggle.onclick = () => { ensureAudio(); muted=!muted; master.gain.setTargetAtTime(muted?.0001:.22,audio.currentTime,.03); soundToggle.textContent=muted?'Sound off':'Sound on'; soundToggle.setAttribute('aria-pressed',String(!muted)); }; makeCave(); draw();
